spring:
  application:
    name: rest-api-gateway
    
server:
  address: 127.0.0.1
  port: 8080
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registry-fetch-interval-seconds: 5
      
zuul:
  routes:
    consumer:
      path: /consumer/**
      stripPrefix: false
      service-id: rest-service-consumer
    provider:
      path: /provider/**
      stripPrefix: false
      service-id: rest-service-provider

rest-service-consumer:
  ribbon:
    ReadTimeout: 30000
    ConnectTimeout: 30000
    ServerListRefreshInterval: 5000
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    
rest-service-provider:
  ribbon:
    ReadTimeout: 30000
    ConnectTimeout: 30000
    ServerListRefreshInterval: 5000
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
         
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000